import type { Metadata } from "next";
import localFont from 'next/font/local';

import {Toaster} from "sonner";
import {Providers} from "./providers";
import HeaderGradient from "@/app/components/header-gradient";


import "./globals.css";
import { ViewTransitions } from "next-view-transitions";

const poppins = localFont({
  src: [
    {
      path: '../../public/fonts/Poppins-Regular.ttf',
      weight: '400'
    },
    {
      path: '../../public/fonts/Poppins-Medium.ttf',
      weight: '500'
    },
    {
      path: '../../public/fonts/Poppins-SemiBold.ttf',
      weight: '600'
    },
    {
      path: '../../public/fonts/Poppins-Bold.ttf',
      weight: '700'
    }
  ],
  variable: '--font-poppins'
})

const kodemono = localFont({
  src: [
    {
      path: '../../public/fonts/KodeMono-Regular.ttf',
      weight: '400'
    },
    {
      path: '../../public/fonts/KodeMono-Medium.ttf',
      weight: '500'
    },
    {
      path: '../../public/fonts/KodeMono-SemiBold.ttf',
      weight: '600'
    },
    {
      path: '../../public/fonts/KodeMono-Bold.ttf',
      weight: '700'
    }
  ],
  variable: '--font-kodemono'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <ViewTransitions>
            <html lang="en">
                <body id='background' className={`${poppins.variable} font-sans ${kodemono.variable} font-mono bg-[#F7F7F7]`}>
                    {/* <div className="-zs-50"> */}
                    <Toaster position="bottom-right" richColors />
                    {/* </div> */}
                    <HeaderGradient/>
                    <Providers>
                    <div  className="absolute w-[70vw] h-[10rem] -left-[5rem] -top-[1rem] bg-[#b3faed] bg-opacity-50 rotate-[-10deg] blur-3xl" />
                    {/* <div className="min-h-[100vh] backdrop-blur-2xl"> */}
                        <div  className="min-h-[100vh] select-none">
                            {children}
                        </div>
                    </Providers>
                </body>
            </html>
        </ViewTransitions>
    );
}
