allowBuilds:
  '@heroui/shared-utils': true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  '@tsparticles/engine': true
  core-js: true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
